language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - git clone git://github.com/pokermania/pokerdistutils.git /tmp/pokerdistutils && sudo pip install /tmp/pokerdistutils
 - git clone https://github.com/pokermania/reflogging /tmp/reflogging && sudo pip install /tmp/reflogging
 - pip install simplejson

# command to run tests, e.g. python setup.py test
script:  python setup.py test -p
