language: python
python:
  - "2.7"
  - "2.6"

install:
 - pip install http://github.com/pokermania/pokerdistutils/archive/master.zip
 - pip install http://github.com/pokermania/reflogging/archive/master.zip
 - pip install simplejson
 - pip install .

script: python setup.py test -p
