language: python
python:
  - "2.7"
  - "2.6"

install:
 - pip install -U pip
 - pip install
    nose
    rednose
    simplejson
    git+git://github.com/pokermania/reflogging.git

script: nosetests --rednose tests
